apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gwg24fz4x-dotnet-basic
  janus-idp.io/tekton: gwg24fz4x-dotnet-basic
  backstage.io/kubernetes-id: gwg24fz4x-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gwg24fz4x-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
